### ISSUE TITLE
[3pts] Set up Kanban board

### ISSUE THREAD

**Issue by BereketRetta** [BereketRetta/Ruby_Capstone#8]
Set up kanban board and assigned roles to each team member
The number of team members:

@BereketRetta
@SirriRyisa 

This is the link to the [Project](https://github.com/BereketRetta/Ruby_Capstone/projects/2)

**Comment by elyor-doniyorov** [comment]
Hi @BereketRetta and @SirriRyisa, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [x] Kindly add `In review` column too. Because currently you have three columns `To do`, `In progress`, `Done`.
- [ ] It would be better if you add a description for every tasks.
- [x] Please make sure if all cards are assigned to team members. You should see a circle with user's avatar on each card. See the example below:
<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/67087664/167590503-0d6a0867-6028-4a19-b902-285f7f981653.png">

- [x] Please make sure that all requirements listed as [group tasks](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md#group-task)  have a corresponding card in the Kanban board. Currently you only have created `Create Item class in a separate .rb file` and `Create a main.rb file that will serve as your console app entry-point.` cards. Kindly create also the other 4 cards.
- [x] Also, I noticed that you have created unnecessary cards those belong to team member 3 or 4. For example, `Create a Game class in a separate .rb file.` is for member 3, etc. Please find them by comparing [these](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) tasks list in the link and remove them and instead make cards from `member 1 and 2 tasks` .
- [x] After you do all suggested changes please make sure the number of points for each student  ([Xpt] in the card title) has no significantly (difference >= 5 points) more or less points than others.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @BereketRetta and @SirriRyisa,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- [x] **@SirriRyisa has 19 points, while @BereketRetta has 24 points. Your task points defer by 5 points. After your implementations, kindly ensure that your task points do not defer by more than 4 points.**

- [x] **You are yet to implement the creation of the 4 tasks as requested previously. You only have the points for the creation of item class and main. Kindly add the rest.**

  ![bereket-3](https://user-images.githubusercontent.com/36542986/167623189-594db217-2685-4f06-b479-4fff75d86ce3.jpg)

- [x] **You are yet to add descriptions for some of your tasks. Some of your tasks have no description or a vague **`Description to be added`**. Kindly add fitting descriptions for **ALL** your tasks.**

  No description | Invalid description
  :---:|:---:
  ![bereket-1](https://user-images.githubusercontent.com/36542986/167623634-8a8cb8d9-55ea-443c-be55-4a4ee450471c.PNG) | ![bereket-2](https://user-images.githubusercontent.com/36542986/167623657-0f5370a3-e6ef-41c0-a728-80fa18afa987.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @TedLivist,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

 ## Required Changes ♻️

- [x] You still have 1 card without a description provided, and another with "description to be added" which is invalid.  Please, write the required descriptions.  Just think about the work you are going to do for the steps, and write a short description! 💪 
- [x] You are still missing 4 group tasks, as requested by the previous reviewer.  Please add them.

## Explanation

![image](https://user-images.githubusercontent.com/57421823/167780055-7652a639-3892-427d-9f74-c111f8b7e227.png)

Each main item needs a task.  I drew arrows for the tasks you are missing.  Just add them, write a description, descriptive title, and points for them.  Remember to assign them to someone, so the total points difference for each team member is still < 4.

Kindly remember this Kanban board is part of your capstone project!  Let's get it right you now have all the info you need 💪 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by arslanbisharat** [comment]
Hi,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by arslanbisharat** [comment]
Hi,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
